# copied from https://github.com/PharmaLedger-IMI/quorum-docker/blob/e8b03aa15523263de739985ba5981df50c179b23/blockchain-explorer/docker-compose.yml
version: "3.6"
x-restart-def:
  &restart-def
  restart_policy:
    condition: on-failure
    delay: 15s
    max_attempts: 3
    window: 120s

services:
  api:
    << : *restart-def
    image: web3labs/epirus-free-api:latest
    environment:
      - NODE_ENDPOINT=${NODE_ENDPOINT}
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - REINDEX_ENDPOINT=http://ingestion/reindex/
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus

  mongodb:
    << : *restart-def
    image: mongo:latest
    ports:
      - 27017:27017
    entrypoint: mongod --logpath=/dev/null --bind_ip "0.0.0.0"
    networks:
      - epirus

  web:
    << : *restart-def
    image: web3labs/epirus-free-web:latest
    environment:
      - API_URL=/api
    depends_on:
      - api
    networks:
      - epirus

  ingestion:
    << : *restart-def
    image: web3labs/epirus-free-ingestion:latest
    environment:
      - NODE_ENDPOINT=${NODE_ENDPOINT}
      - MONGO_CLIENT_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb
    networks:
      - epirus

  nginx:
    << : *restart-def
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 8700:80
    depends_on:
      - api
      - web
    networks:
      - epirus

networks:
  epirus:
    name: epirus-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
