# The following environment variables are substituted if present
# * QUORUM_CONSENSUS: default to istanbul
# * QUORUM_DOCKER_IMAGE: default to quorumengineering/quorum:2.5.0
# * QUORUM_TX_MANAGER_DOCKER_IMAGE: default to quorumengineering/tessera:0.10.2
# * QUORUM_GETH_ARGS: extra geth arguments to be included when running geth
# To use Constellation, set QUORUM_TX_MANAGER_DOCKER_IMAGE to Constellation docker image,
# e.g.: QUORUM_TX_MANAGER_DOCKER_IMAGE=quorumengineering/constellation:0.3.2 docker-compose up -d
# To use Remix, set QUORUM_GETH_ARGS="--rpccorsdomain https://remix.ethereum.org"
version: "2.3"
x-quorum-def:
  &quorum-def
  restart: "on-failure"
  image: "${DOCKER_REGISTRY:-}${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.5.0}"
  healthcheck:
    test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:${QUORUM_RPC_PORT:-8545}"]
    interval: 3s
    timeout: 3s
    retries: 10
    start_period: 5s
  labels:
    com.quorum.consensus: ${QUORUM_CONSENSUS:-istanbul}
  entrypoint:
    - /bin/sh
    - -c
    - |
      UDS_WAIT=10
      if [ "$${PRIVATE_CONFIG}" != "ignore" ]; then
      for i in $$(seq 1 100)
      do
        set -e
        if [ -S $${PRIVATE_CONFIG} ] && \
          [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- --proxy off txmanager$${NODE_ID}:${TESSERA_P2P_PORT:-9000}/upcheck)" ];
        then break
        else
          echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
          sleep $${UDS_WAIT}
        fi
      done
      fi
      apk add wireguard-tools
      modprobe wireguard
      wg-quick up wg0
      DDIR=/qdata/dd
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      cp -r /examples/dd$${NODE_ID}/* $${DDIR}
      cat /examples/dd$${NODE_ID}/hosts >> /etc/hosts
      cp /examples/dd$${NODE_ID}/permissioned-nodes.json $${DDIR}/static-nodes.json
      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
      cat $${DDIR}/static-nodes.json
      GENESIS_FILE="/examples/dd$${NODE_ID}/genesis.json"
      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
      GETH_ARGS_raft="--raft --raftport ${QUORUM_RAFT_PORT:-50400}"
      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
      EXTRA_ARGS="${QUORUM_GETH_ARGS:-}"
      geth --datadir $${DDIR} init $${GENESIS_FILE}
      geth \
        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
        --datadir $${DDIR} \
        --permissioned \
        --nodiscover \
        --nousb \
        --verbosity 5 \
        --networkid $${NETWORK_ID} \
        --http \
        --http.corsdomain "*" \
        --http.vhosts "*" \
        --http.addr 0.0.0.0 \
        --http.port ${QUORUM_RPC_PORT:-8545} \
        --http.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --ws \
        --ws.addr 0.0.0.0 \
        --ws.origins "*" \
        --ws.port ${QUORUM_WS_PORT:-8546} \
        --ws.api admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
        --port ${QUORUM_P2P_PORT:-21000} \
        --allow-insecure-unlock \
        --unlock 0 \
        --password $${DDIR}/keystore/password.txt \
        --syncmode full \
        #--verbosity 5 \
        #--debug \
        #--vmdebug \
        #--bootnodes 'enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@172.16.81.11:30303'
        $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}} \
        $$EXTRA_ARGS
  expose:
    - "${QUORUM_P2P_PORT:-21000}"
    - "${QUORUM_RAFT_PORT:-50400}"
x-tx-manager-def:
  &tx-manager-def
  image: "${DOCKER_REGISTRY:-}${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.2}"
  restart: "no"
  healthcheck:
    test: ["CMD-SHELL", "[ -S /qdata/tm/tm.ipc ] || exit 1"]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s
  entrypoint:
    - /bin/sh
    - -c
    - |
      apk add wireguard-tools
      modprobe wireguard
      wg-quick up wg0
      DDIR=/qdata/tm
      rm -rf $${DDIR}
      mkdir -p $${DDIR}
      cat /examples/c$${NODE_ID}/hosts >> /etc/hosts
      DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.2}"
      TX_MANAGER=$$(echo $${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$$/\1/g')
      echo "TxManager: $${TX_MANAGER}"
      case $${TX_MANAGER}
      in
        tessera)
          cp -r /examples/c$${NODE_ID}/* $${DDIR}
          #extract the tessera version from the jar
          TESSERA_VERSION=$$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
          echo "Tessera version (extracted from manifest file): $${TESSERA_VERSION}"
          TESSERA_CONFIG_TYPE="-09"
          echo Config type $${TESSERA_CONFIG_TYPE}
          HOSTNAME=$$(hostname -i)
          sed -i "s,%THIS_PRIV_KEY%,$${DDIR}/tm.key,g" $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          sed -i "s,%THIS_PUB_KEY%,$${DDIR}/tm.pub,g" $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          sed -i 's,etc/quorum/,,g' $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          sed -i 's/%QUORUM-NODE\([0-9]\)_SERVICE_HOST%/txmanager\1/g' $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          sed -i "s/%THIS_SERVICE_HOST%/$${HOSTNAME}/g" $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          cat $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
          ;;
        *)
          echo "Invalid Transaction Manager"
          exit 1
          ;;
      esac
  expose:
    - "${TESSERA_P2P_PORT:-9000}"
    - "${TESSERA_3PARTY_PORT:-9080}"
services:
  leafnode:
    << : *quorum-def
    container_name: leafnode-pdmfc-ibft
    hostname: leafnode
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "27000:8545"
      - "28000:8546"
      - "29000:8547"
    volumes:
      - vol1:/qdata
      - ./qdata:/examples:ro
      - /lib/modules:/lib/modules
      - ./wireguard/leaf:/etc/wireguard
    depends_on:
      - txmanager_leaf1
    environment:
      - PRIVATE_CONFIG=/qdata/tm/tm.ipc
      - NODE_ID=leaf
    networks:
      pdmfc-leaf-net:
        ipv4_address: 172.16.82.120
  txmanagerleaf:
    << : *tx-manager-def
    container_name: txmanager-leaf1-pdmfc-ibft
    hostname: txmanagerleaf
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "9981:9080"
    volumes:
      - vol1:/qdata
      - ./qdata:/examples:ro
      - ./wireguard/tessera:/etc/wireguard
    networks:
      pdmfc-leaf-net:
        ipv4_address: 172.16.82.121
    environment:
      - NODE_ID=leaf
networks:
  pdmfc-leaf-net:
    name: pdmfc-leaf-net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.82.0/24

volumes:
  "vol1":
