#from node:12
FROM node:12-alpine


RUN apk add yarn git
RUN yarn global add truffle


# Create app directory
WORKDIR /usr/node/app
COPY . .
#COPY package*.json ./
RUN npm install
#COPY . .

CMD [ "sh","-c", "truffle migrate && node index.js" ]
#CMD [ "truffle", "migrate" ]

